
import { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

export interface RestaurantListing {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: string;
  address: string;
  phone?: string;
  whatsapp?: string;
  website?: string;
  email?: string;
  image_url?: string;
  latitude?: number | null;
  longitude?: number | null;
  hours: Record<string, string>;
  gallery_images: string[];
  menu_images: string[];
  approved: boolean;
  user_id: string;
  created_at: string;
  updated_at: string;
  is_premium: boolean;
  display_order: number;
  closed_for_season: boolean;
}

export const useRestaurantListings = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [userRestaurants, setUserRestaurants] = useState<RestaurantListing[]>([]);

  const fetchUserRestaurants = async () => {
    if (!user) return;
    
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('restaurant_listings')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      
      // Transform the data to match our interface with proper type handling
      const transformedData: RestaurantListing[] = data?.map(item => ({
        ...item,
        slug: item.slug || '', // Use database slug
        hours: typeof item.hours === 'object' && item.hours !== null ? 
          item.hours as Record<string, string> : {},
        gallery_images: Array.isArray(item.gallery_images) ? 
          item.gallery_images as string[] : [],
        menu_images: Array.isArray(item.menu_images) ? 
          item.menu_images as string[] : [],
        is_premium: item.is_premium || false,
        display_order: item.display_order || 0,
        closed_for_season: item.closed_for_season || false,
      })) || [];
      
      setUserRestaurants(transformedData);
    } catch (error) {
      console.error('Error fetching user restaurants:', error);
      toast({
        title: "Error",
        description: "Failed to fetch your restaurants",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const submitRestaurant = async (restaurantData: Omit<RestaurantListing, 'id' | 'slug' | 'user_id' | 'created_at' | 'updated_at' | 'approved' | 'is_premium' | 'display_order' | 'closed_for_season'>) => {
    if (!user) throw new Error('User not authenticated');

    const { error } = await supabase
      .from('restaurant_listings')
      .insert({
        ...restaurantData,
        user_id: user.id,
        slug: null, // Will be auto-generated by database trigger
      });

    if (error) throw error;

    toast({
      title: "Restaurant submitted!",
      description: "Your restaurant has been submitted for review.",
    });

    fetchUserRestaurants();
  };

  useEffect(() => {
    fetchUserRestaurants();
  }, [user]);

  return {
    userRestaurants,
    loading,
    submitRestaurant,
    fetchUserRestaurants,
  };
};
